apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: foobar-api-mcs
  namespace: default
spec:
  template:
    spec:
      selector:
        app: foobar-api
      ports:
      - name: foobar-api
        protocol: TCP
        port: 8080
        targetPort: 8080
